AI_Struct = {
 {Name = 'Tg_ST1', Address = 'A2.6:1', Comment = 'Температура газа за СТ 1', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:2a,XAI6:2b', Node = 'БУ'}
 ,{Name = 'Tg_ST2', Address = 'A2.6:2', Comment = 'Температура газа за СТ 2', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:3a,XAI6:3b', Node = 'БУ'}
 ,{Name = 'Tg_ST3', Address = 'A2.7:1', Comment = 'Температура газа за СТ 3', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:4a,XAI6:4b', Node = 'БУ'}
 ,{Name = 'Tg_ST4', Address = 'A2.7:2', Comment = 'Температура газа за СТ 4', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:5a,XAI6:5b', Node = 'БУ'}
 ,{Name = 'Tg_ST5', Address = 'A2.8:1', Comment = 'Температура газа за СТ 5', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:6a,XAI6:6b', Node = 'БУ'}
 ,{Name = 'Tg_ST6', Address = 'A2.8:2', Comment = 'Температура газа за СТ 6', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:7a,XAI6:7b', Node = 'БУ'}
 ,{Name = 'Tg_ST7', Address = 'A2.9:1', Comment = 'Температура газа за СТ 7', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:8a,XAI6:8b', Node = 'БУ'}
 ,{Name = 'Tg_ST8', Address = 'A2.9:2', Comment = 'Температура газа за СТ 8', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:9a,XAI6:9b', Node = 'БУ'}
 ,{Name = 'Tg_ST9', Address = 'A2.10:1', Comment = 'Температура газа за СТ 9', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:10a,XAI6:10b', Node = 'БУ'}
 ,{Name = 'Tg_ST10', Address = 'A2.10:2', Comment = 'Температура газа за СТ 10', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:11a,XAI6:11b', Node = 'БУ'}
 ,{Name = 'Tg_ST11', Address = 'A2.11:1', Comment = 'Температура газа за СТ 11', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:12a,XAI6:12b', Node = 'БУ'}
 ,{Name = 'Tg_ST12', Address = 'A2.11:2', Comment = 'Температура газа за СТ 12', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:13a,XAI6:13b', Node = 'БУ'}
 ,{Name = 'Tair_GG', Address = 'A2.12:1', Comment = 'Т воздуха за компрессором ГГ', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:1a,XAI6:1b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_01', Address = 'A2.12:2', Comment = 'Резерв (ХА)', LL = '0', HL = '1200', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI6:14a,XAI6:14b', Node = 'БУ'}
 ,{Name = 'Tg_GG_start1', Address = 'A2.13:1', Comment = 'Полная температура газа за турбиной газогенератора на запуске (1 канал)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:1a,XAI4:1b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_02', Address = 'A2.13:2', Comment = 'Не подключен (модуль с быстродействующим каналом)', LL = '0', HL = '0', UM = '', TypeCh = '', TypeADC ='thermocouple', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Tg_GG_start2', Address = 'A2.14:1', Comment = 'Полная температура газа за турбиной газогенератора на запуске (2 канал)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:2a,XAI4:2b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_03', Address = 'A2.14:2', Comment = 'Не подключен  (модуль с быстродействующим каналом)', LL = '0', HL = '0', UM = '°С', TypeCh = '', TypeADC ='thermocouple', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode1', Address = 'A2.15:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 1)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:3a,XAI4:3b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode2', Address = 'A2.15:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 2)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:4a,XAI4:4b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode3', Address = 'A2.16:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 3)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:5a,XAI4:5b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode4', Address = 'A2.16:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 4)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:6a,XAI4:6b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode5', Address = 'A2.17:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 5)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:7a,XAI4:7b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode6', Address = 'A2.17:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 6)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:8a,XAI4:8b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode7', Address = 'A2.18:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 7)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:9a,XAI4:9b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode8', Address = 'A2.18:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 8)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:10a,XAI4:10b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode9', Address = 'A2.19:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 9)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:11a,XAI4:11b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode10', Address = 'A2.19:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 10)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:12a,XAI4:12b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode11', Address = 'A2.20:1', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 11)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:13a,XAI4:13b', Node = 'БУ'}
 ,{Name = 'Tg_GG_mode12', Address = 'A2.20:2', Comment = 'Полная температура газа за турбиной газогенератора на режимах (канал 12)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:14a,XAI4:14b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_04', Address = 'A2.21:1', Comment = 'Резерв (ХА)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:15a,XAI4:15b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_05', Address = 'A2.21:2', Comment = 'Резерв (ХА)', LL = '-60', HL = '1300', UM = '°С', TypeCh = 'ХА', TypeADC ='thermocouple', AdrCh ='БУ:XAI4:16a,XAI4:16b', Node = 'БУ'}
 ,{Name = 'Tm_inD', Address = 'A2.22:1', Comment = 'Т масла на входе Д', LL = '-98', HL = '98', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:1a,XAI3:1b', Node = 'БУ'}
 ,{Name = 'Tm_outShP', Address = 'A2.22:2', Comment = 'Т масла на выходе из опоры ш/п компрессора ', LL = '-49', HL = '344', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:2a,XAI3:2b', Node = 'БУ'}
 ,{Name = 'Tm_outRP', Address = 'A2.23:1', Comment = 'Т масла на выходе из опоры р/п компрессора ГГ', LL = '-49', HL = '344', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:3a,XAI3:3b', Node = 'БУ'}
 ,{Name = 'Tm_outST', Address = 'A2.23:2', Comment = 'Т масла на выходе из опор СТ', LL = '-49', HL = '344', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:4a,XAI3:4b', Node = 'БУ'}
 ,{Name = 'Tm_MBD', Address = 'A2.24:1', Comment = 'Т масла в МБД', LL = '-91', HL = '90', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:5a,XAI3:5b', Node = 'БУ'}
 ,{Name = 'Tv_KShT', Address = 'A2.24:2', Comment = 'Темп. воздуха под КШТ Д', LL = '-49', HL = '344', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:6a,XAI3:6b', Node = 'БУ'}
 ,{Name = 'Tv_inD', Address = 'A2.25:1', Comment = 'Полная температура воздуха на входе в двигатель', LL = '-60', HL = '80', UM = '°С', TypeCh = '50П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:7a,XAI3:7b', Node = 'БУ'}
 ,{Name = 'Ttg_inTRK', Address = 'A2.25:2', Comment = 'Температура топливного газа перед дозатором', LL = '-50', HL = '100', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:8a,XAI3:8b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_06', Address = 'A2.26:1', Comment = 'Резерв (100М)', LL = '-49', HL = '344', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:9a,XAI3:9b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_07', Address = 'A2.26:2', Comment = 'Резерв (100П)', LL = '-91', HL = '90', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='БУ:XAI3:10a,XAI3:10b', Node = 'БУ'}
 ,{Name = 'Pos_TRK', Address = 'A2.27:1', Comment = 'Положение дозатора', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:внутр,', Node = 'БУ'}
 ,{Name = 'Pos_VNA', Address = 'A2.27:2', Comment = 'Положение ВНА', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:внутр,', Node = 'БУ'}
 ,{Name = 'Set_TRK_KCU', Address = 'A2.28:1', Comment = 'Задание положения дозатора. КЦУ', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:внутр,', Node = 'БУ'}
 ,{Name = 'Set_VNA_KCU', Address = 'A2.28:2', Comment = 'Задание положения ВНА. КЦУ', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:внутр,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_08', Address = 'A2.28:3', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_09', Address = 'A2.28:4', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Pm_inD', Address = 'A2.29:1', Comment = 'Р масла на входе в Д', LL = '0', HL = '0,6', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:1a,XAI1:1b', Node = 'БУ'}
 ,{Name = 'Pm_outD', Address = 'A2.29:2', Comment = 'Р масла на выходе из Д', LL = '0', HL = '160', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:2a,XAI1:2b', Node = 'БУ'}
 ,{Name = 'Lm_MBD', Address = 'A2.29:3', Comment = 'Количество масла в МБД', LL = '0', HL = '900', UM = 'л', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:3a,XAI1:3b', Node = 'БУ'}
 ,{Name = 'Ptg_inSK', Address = 'A2.29:4', Comment = 'Давл. топливн. газа на входе Д (перед СК)', LL = '0', HL = '4', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:4a,XAI1:4b', Node = 'БУ'}
 ,{Name = 'Psufl_D', Address = 'A2.30:1', Comment = 'Р суфлирования Д', LL = '0', HL = '100', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:5a,XAI1:5b', Node = 'БУ'}
 ,{Name = 'Ppg_inStV', Address = 'A2.30:2', Comment = 'Р пуск. газа перед засл. СтВ', LL = '0', HL = '1', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:6a,XAI1:6b', Node = 'БУ'}
 ,{Name = 'Qv_blowD', Address = 'A2.30:3', Comment = 'Расход воздуха через систему обдува  двигателя', LL = '0,3', HL = '30', UM = 'м/с', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:7a,XAI1:7b', Node = 'БУ'}
 ,{Name = 'dPv_filtVOU', Address = 'A2.30:4', Comment = 'dР воздуха на фильтрах блоке ВОУ', LL = '0', HL = '0,63', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:8a,XAI1:8b', Node = 'БУ'}
 ,{Name = 'V_PPD', Address = 'A2.31:1', Comment = 'Виброскорость, передней подвески Д', LL = '0', HL = '100', UM = 'мм/с', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:9a,XAI1:9b', Node = 'БУ'}
 ,{Name = 'V_ZPD', Address = 'A2.31:2', Comment = 'Виброскорость, задней подвески Д', LL = '0', HL = '100', UM = 'мм/с', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:10a,XAI1:10b', Node = 'БУ'}
 ,{Name = 'dPtg_filtClean', Address = 'A2.31:3', Comment = 'dР топл. газа на фильтрах очистки', LL = '0', HL = '63', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:11a,XAI1:11b', Node = 'БУ'}
 ,{Name = 'Ttg_izmDiaphr', Address = 'A2.31:4', Comment = 'Т топл. газа перед измерительной диафрагмой', LL = '-50', HL = '50', UM = '°С', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:12a,XAI1:12b', Node = 'БУ'}
 ,{Name = 'dPtg_izmDiaphr', Address = 'A2.32:1', Comment = 'Перепад Р топл. газа на измерительной диафрагме', LL = '0', HL = '63', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:13a,XAI1:13b', Node = 'БУ'}
 ,{Name = 'Ptg_inIzmDiaphr', Address = 'A2.32:2', Comment = 'Р топл. газа на входе измерительной диаафрагме', LL = '0', HL = '4', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:14a,XAI1:14b', Node = 'БУ'}
 ,{Name = 'dP_Patm_fullPv_inGG', Address = 'A2.32:3', Comment = 'Перепад между Ратм.  и полным Рв на вх. в компрессор ГГ ', LL = '0', HL = '63', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:15a,XAI1:15b', Node = 'БУ'}
 ,{Name = 'dP_Patm_statPv_inGG', Address = 'A2.32:4', Comment = 'Перепад между Ратм.  и статическим Рв на вх. в компрессор ГГ', LL = '0', HL = '16', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI1:16a,XAI1:16b', Node = 'БУ'}
 ,{Name = 'Pv_razPolST', Address = 'A2.33:1', Comment = 'Р воздуха в разгрузочной полости СТ', LL = '0', HL = '600', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:1a,XAI2:1b', Node = 'БУ'}
 ,{Name = 'Pg_bST', Address = 'A2.33:2', Comment = 'Полное Р газа за турбиной ГГ', LL = '0', HL = '600', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:2a,XAI2:2b', Node = 'БУ'}
 ,{Name = 'dP_Patm_fullPg_bST', Address = 'A2.33:3', Comment = 'Перепад между атмосферным Р и полным Р газа за СТ', LL = '0', HL = '16', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:3a,XAI2:3b', Node = 'БУ'}
 ,{Name = 'Pv_razPolGG', Address = 'A2.33:4', Comment = 'Р воздуха в разгрузочной полости компрессора ГГ', LL = '0', HL = '160', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:4a,XAI2:4b', Node = 'БУ'}
 ,{Name = 'Patm', Address = 'A2.34:1', Comment = 'Атмосферное Р наружного воздуха', LL = '80', HL = '120', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:5a,XAI2:5b', Node = 'БУ'}
 ,{Name = 'Pv_bGG', Address = 'A2.34:2', Comment = 'Полное давление воздуха за компрессором газогенератора', LL = '0', HL = '4', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:6a,XAI2:6b', Node = 'БУ'}
 ,{Name = 'Ptg_inTRK', Address = 'A2.34:3', Comment = 'Давление топливного газа на входе в САУ (перед дозатором газа)', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:7a,XAI2:7b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_10', Address = 'A2.34:4', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:8a,XAI2:8b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_11', Address = 'A2.35:1', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:9a,XAI2:9b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_12', Address = 'A2.35:2', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:10a,XAI2:10b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_13', Address = 'A2.35:3', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:11a,XAI2:11b', Node = 'БУ'}
 ,{Name = 'Reserv_AI_14', Address = 'A2.35:4', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:XAI2:12a,XAI2:12b', Node = 'БУ'}
 ,{Name = 'Set_TRK', Address = 'A4.3:1', Comment = 'Задание положения дозатора', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Set_VNA', Address = 'A4.3:2', Comment = 'Задание положения ВНА', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_15', Address = 'A4.3:3', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_16', Address = 'A4.3:4', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_17', Address = 'A4.3:5', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_18', Address = 'A4.3:6', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_19', Address = 'A4.3:7', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Reserv_AI_20', Address = 'A4.3:8', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='БУ:,', Node = 'БУ'}
 ,{Name = 'Tw_inUTO', Address = 'А30.1:1', Comment = 'Т воды на входе теплообменника', LL = '-91', HL = '91', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:1a,XAI10:1b', Node = 'ЭС'}
 ,{Name = 'Tw_outUTO', Address = 'А30.1:2', Comment = 'Т воды на выходе теплообменника', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:2a,XAI10:2b', Node = 'ЭС'}
 ,{Name = 'Tv_bayN', Address = 'А30.2:1', Comment = 'Т воздуха в отсеке Н', LL = '-91', HL = '90', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЭС:F11:1,F11:2', Node = 'ЭС'}
 ,{Name = 'Tv_bayGTU', Address = 'А30.2:2', Comment = 'Т воздуха в отсеке ГТУ', LL = '-91', HL = '90', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:3a,XAI10:3b', Node = 'ЭС'}
 ,{Name = 'Tv_bayBU', Address = 'А30.3:1', Comment = 'Т воздуха в отсеке БУ', LL = '-98', HL = '98', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:4a,XAI10:4b', Node = 'ЭС'}
 ,{Name = 'Tv_OMA', Address = 'А30.3:2', Comment = 'Т воздуха в ОМА', LL = '-98', HL = '98', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:5a,XAI10:5b', Node = 'ЭС'}
 ,{Name = 'Tv_OPT', Address = 'А30.4:1', Comment = 'Т воздуха в ОПТ', LL = '-98', HL = '98', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:6a,XAI10:6b', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_21', Address = 'А30.4:2', Comment = 'Резерв', LL = '-98', HL = '98', UM = '°С', TypeCh = '100П', TypeADC ='thermocouple', AdrCh ='ЭС:XAI10:7a,XAI10:7b', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_22', Address = 'А30.5:1', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:1a,XAI9:1b', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_23', Address = 'А30.5:2', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:2a,XAI9:2b', Node = 'ЭС'}
 ,{Name = 'F_VOD1', Address = 'А30.5:3', Comment = 'Частота вращения вентилятора №1 обдува двигателя', LL = '0', HL = '100', UM = '%', TypeCh = '0-10 В', TypeADC ='0_10V', AdrCh ='ЭС:XAI9:3a,XAI9:3b', Node = 'ЭС'}
 ,{Name = 'F_VOD2', Address = 'А30.5:4', Comment = 'Частота вращения вентилятора №2 обдува двигателя', LL = '0', HL = '100', UM = '%', TypeCh = '0-10 В', TypeADC ='0_10V', AdrCh ='ЭС:XAI9:4a,XAI9:4b', Node = 'ЭС'}
 ,{Name = 'Tair', Address = 'А30.6:1', Comment = 'Т наружного воздуха', LL = '-40', HL = '60', UM = '°С', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:5a,XAI9:5b', Node = 'ЭС'}
 ,{Name = 'Wet', Address = 'А30.6:2', Comment = 'Относительная влажность наружного воздуха', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:6a,XAI9:6b', Node = 'ЭС'}
 ,{Name = 'dPv_KShT_bayGTU', Address = 'А30.6:3', Comment = 'Перепад давления воздуха между  КШТ и отсеком ГТУ', LL = '0', HL = '0,63', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:7a,XAI9:7b', Node = 'ЭС'}
 ,{Name = 'dPv_atm_blowTransm', Address = 'А30.6:4', Comment = 'dР воздуха между атмосферой и зоной обдува трансмиссии', LL = '0', HL = '1,6', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:8a,XAI9:8b', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_24', Address = 'А30.7:1', Comment = 'Резерв', LL = '0', HL = '10', UM = 'В', TypeCh = '0-10 В', TypeADC ='0_10V', AdrCh ='ЭС:XAI9:9a,XAI9:9b', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_25', Address = 'А30.7:2', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:XAI9:10a,XAI9:10b', Node = 'ЭС'}
 ,{Name = 'Set_VOD1_KCU', Address = 'А30.7:3', Comment = 'Управляющий сигнал на регулятор частоты вращения ВОД1. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'Set_VOD2_KCU', Address = 'А30.7:4', Comment = 'Управляющий сигнал на регулятор частоты вращения ВОД2. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '0-10 В', TypeADC ='0_10V', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_26', Address = 'А30.8:1', Comment = 'Резерв. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'Reserv_AI_27', Address = 'А30.8:2', Comment = 'Резерв. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'U_main', Address = 'А30.8:3', Comment = 'Измерение основного питания САУ', LL = '0', HL = '370', UM = 'В', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'U_reserv', Address = 'А30.8:4', Comment = 'Измерение резервного питания САУ', LL = '0', HL = '370', UM = 'В', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЭС:,', Node = 'ЭС'}
 ,{Name = 'T_PON', Address = 'А20.1:1', Comment = 'Темпер. переднего опорного подшипника нагнетателя ', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F1:1,F1:2', Node = 'ЦБК'}
 ,{Name = 'T_ZON', Address = 'А20.1:2', Comment = 'Темпер. заднего опорного подшипника нагнетателя', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F2:1,F2:2', Node = 'ЦБК'}
 ,{Name = 'T_UPP', Address = 'А20.2:1', Comment = 'Температура упорного подшипника со стороны привода', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F3:1,F3:2', Node = 'ЦБК'}
 ,{Name = 'T_UPN', Address = 'А20.2:2', Comment = 'Температура упорного подшипника со стороны насоса', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F4:1,F4:2', Node = 'ЦБК'}
 ,{Name = 'Tg_inN', Address = 'А20.3:1', Comment = 'Темп. газа на входе Н', LL = '-91', HL = '70', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F5:1,F5:2', Node = 'ЦБК'}
 ,{Name = 'Tg_outN', Address = 'А20.3:2', Comment = 'Темп. газа на выходе Н', LL = '-45', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F6:1,F6:2', Node = 'ЦБК'}
 ,{Name = 'Tm_MBN', Address = 'А20.4:1', Comment = 'Т масла в МБН', LL = '-91', HL = '90', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F7:1,F7:2', Node = 'ЦБК'}
 ,{Name = 'Tm_inAVOMN', Address = 'А20.4:2', Comment = 'Т масла на выходе АВОМ Н', LL = '-91', HL = '90', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F8:1,F8:2', Node = 'ЦБК'}
 ,{Name = 'Reserv_AI_28', Address = 'А20.5:1', Comment = 'Резерв', LL = '-45', HL = '200', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:F9:1,F9:2', Node = 'ЦБК'}
 ,{Name = 'Reserv_AI_29', Address = 'А20.5:2', Comment = 'не подключен', LL = '0', HL = '0', UM = '', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='ЦБК:,', Node = 'ЦБК'}
 ,{Name = 'dP_konfN', Address = 'А20.6:1', Comment = 'Перепад P газа на конфузоре Н', LL = '0', HL = '16', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:1a,XAI7:1b', Node = 'ЦБК'}
 ,{Name = 'Pg_inN', Address = 'А20.6:2', Comment = 'P газа на входе нагнетателя', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:2a,XAI7:2b', Node = 'ЦБК'}
 ,{Name = 'Pg_outN', Address = 'А20.7:1', Comment = 'P газа на выходе нагнетателя', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:3a,XAI7:3b', Node = 'ЦБК'}
 ,{Name = 'Pos_APK', Address = 'А20.7:2', Comment = 'Степень закрытия Mokveld', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:4a,XAI7:4b', Node = 'ЦБК'}
 ,{Name = 'Set_APK', Address = 'А20.8:1', Comment = 'Задание на закрытие Mokveld', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:5a,XAI7:5b', Node = 'ЦБК'}
 ,{Name = 'P_bKr2', Address = 'А20.8:2', Comment = 'Давление после крана 2', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:6a,XAI7:6b', Node = 'ЦБК'}
 ,{Name = 'Reserv_AI_30', Address = 'А20.9:1', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:7a,XAI7:7b', Node = 'ЦБК'}
 ,{Name = 'Reserv_AI_31', Address = 'А20.9:2', Comment = 'Резерв', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:16a,XAI7:16b', Node = 'ЦБК'}
 ,{Name = 'Set_APK_KCU', Address = 'А20.10:1', Comment = 'Управление рег. клапаном Mokveld. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:внутр.,', Node = 'ЦБК'}
 ,{Name = 'Reserv_AI_32', Address = 'А20.10:2', Comment = 'Резерв. КЦУ', LL = '4', HL = '20', UM = 'мА', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:внутр.,', Node = 'ЦБК'}
 ,{Name = 'dPmg', Address = 'А20.11:1', Comment = 'dР "масло-газ" в системе уплотнений Н', LL = '0', HL = '0,63', UM = 'Мпа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:8a,XAI7:8b', Node = 'ЦБК'}
 ,{Name = 'Pmsm', Address = 'А20.11:2', Comment = 'Р масла смазки упорного подшипника Н', LL = '0', HL = '0,6', UM = 'Мпа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:9a,XAI7:9b', Node = 'ЦБК'}
 ,{Name = 'Lm_MBN', Address = 'А20.11:3', Comment = 'Уровень масла в МБН', LL = '0', HL = '700', UM = 'мм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:10a,XAI7:10b', Node = 'ЦБК'}
 ,{Name = 'V_PON_v', Address = 'А20.11:4', Comment = 'Виброперемещение ротора Н в передней опоре - вертикальная', LL = '0', HL = '250', UM = 'мкм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:11a,XAI7:11b', Node = 'ЦБК'}
 ,{Name = 'V_PON_g', Address = 'А20.12:1', Comment = 'Виброперемещение ротора Н в передней опоре - горизонтальная', LL = '0', HL = '250', UM = 'мкм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:12a,XAI7:12b', Node = 'ЦБК'}
 ,{Name = 'V_ZON_v', Address = 'А20.12:2', Comment = 'Виброперемещение ротора Н в задней опоре - вертикальная', LL = '0', HL = '250', UM = 'мкм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:13a,XAI7:13b', Node = 'ЦБК'}
 ,{Name = 'V_ZON_g', Address = 'А20.12:3', Comment = 'Виброперемещение ротора Н в задней опоре - горизонтальная', LL = '0', HL = '100', UM = 'мкм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:14a,XAI7:14b', Node = 'ЦБК'}
 ,{Name = 'Os_N', Address = 'А20.12:4', Comment = 'Осевой сдвиг ротора  - в сторону Д (+) -в сторону Н (-)', LL = '-1', HL = '1', UM = 'мм', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='ЦБК:XAI7:15a,XAI7:15b', Node = 'ЦБК'}
 ,{Name = 'Tg_inAGMB', Address = 'А40.3:1', Comment = 'Температура газа на входе в АГМБ', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tm_inGMTD', Address = 'А40.3:2', Comment = 'Температура масла двигателя на входе в ГМТ Д', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tm_outGMTD', Address = 'А40.4:1', Comment = 'Температура масла двигателя на выходе из ГМТ Д', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tg_outAGMB', Address = 'А40.4:2', Comment = 'Температура газа на выходе из АГМБ', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tm_inGMTN', Address = 'А40.5:1', Comment = 'Температура масла двигателя на входе в ГМТ К', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tm_outGMTN', Address = 'А40.5:2', Comment = 'Температура масла двигателя на выходе из ГМТ К', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Tm_outSeKTeplST', Address = 'А40.6:1', Comment = 'Температура масла компрессора на выходе из секции теплообменной СТ', LL = '-50', HL = '200', UM = '°С', TypeCh = '100Pt', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Reserv_AI_33', Address = 'А40.6:2', Comment = 'Резерв', LL = '-60', HL = '150', UM = '°С', TypeCh = '100М', TypeADC ='thermocouple', AdrCh ='АМГБ:,', Node = 'АМГБ'}
 ,{Name = 'Pg_inAGMB', Address = 'А40.7:1', Comment = 'Давление газа на входе в АГМБ', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-1A,XAI1-1C', Node = 'АМГБ'}
 ,{Name = 'Pm_inGMTD', Address = 'А40.7:2', Comment = 'Давление масла двигателя на входе в ГМТ Д', LL = '0', HL = '1,6', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-2A,XAI1-2C', Node = 'АМГБ'}
 ,{Name = 'Pg_outAGMB', Address = 'А40.7:3', Comment = 'Давление газа на выходе в АГМБ', LL = '0', HL = '10', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-3A,XAI1-3C', Node = 'АМГБ'}
 ,{Name = 'Pm_inGMTN', Address = 'А40.7:4', Comment = 'Давление масла компрессора на входе в ГМТ К', LL = '0', HL = '1,6', UM = 'МПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-4A,XAI1-4C', Node = 'АМГБ'}
 ,{Name = 'dP_filtGaz', Address = 'А40.8:1', Comment = 'Перепад давления на фильтре газа', LL = '0', HL = '250', UM = 'кПа', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-5A,XAI1-5C', Node = 'АМГБ'}
 ,{Name = 'T_povSekTeplST', Address = 'А40.8:2', Comment = 'Температура поверхности секции теплообменной СТ', LL = '-50', HL = '200', UM = '°С', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-6A,XAI1-6C', Node = 'АМГБ'}
 ,{Name = 'Gaz_air', Address = 'А40.8:3', Comment = 'Степень загазованности воздуха', LL = '0', HL = '100', UM = '%', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-7В,XAI1-7C', Node = 'АМГБ'}
 ,{Name = 'flameEq', Address = 'А40.8:4', Comment = 'Пламя в оборудовании ', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:XAI1-8В,XAI1-8C', Node = 'АМГБ'}
 ,{Name = 'Reserv_AI_34', Address = 'А40.9:1', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:не подкл.,', Node = 'АМГБ'}
 ,{Name = 'Reserv_AI_35', Address = 'А40.9:2', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:не подкл.,', Node = 'АМГБ'}
 ,{Name = 'Reserv_AI_36', Address = 'А40.9:3', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:не подкл.,', Node = 'АМГБ'}
 ,{Name = 'Reserv_AI_37', Address = 'А40.9:4', Comment = 'Резерв', LL = '0', HL = '0', UM = '', TypeCh = '4-20 мА', TypeADC ='4_20mA', AdrCh ='АМГБ:не подкл.,', Node = 'АМГБ'}
}
